In [2]:
import os
import cv2
import time
import numpy as np
import matplotlib.pyplot as plt

In [3]:

frameset_path = r'C:\Users\Legion\Desktop\Internship_IIT\UCSD_Anomaly_Dataset.v1p2\UCSDped1\Train\Train001'

list_frames = os.listdir(frameset_path)
list_frames.remove('._.DS_Store')
list_frames.remove('.DS_Store')

ref_frame = cv2.imread(os.path.join(frameset_path,list_frames[0]),0)


#cap = cv2.VideoCapture('slow.flv')
# params for ShiTomasi corner detection
feature_params = dict( maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7,
                       blockSize = 7 )


# Parameters for lucas kanade optical flow
lk_params = dict( winSize  = (15,15),
                  maxLevel = 2,
                  criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 0.03))

# Create some random colors
color = np.random.randint(0,255,(100,3))

#old_gray = cv2.cvtColor(ref_frame, cv2.COLOR_BGR2GRAY)

p0 = cv2.goodFeaturesToTrack(ref_frame, mask = None, **feature_params)

color_ref_frame = cv2.cvtColor(ref_frame, cv2.COLOR_GRAY2BGR)

# Create a mask image for drawing purposes
mask = np.zeros_like(color_ref_frame)


for frame_name in list_frames[1:]:
    
    frame_path = os.path.join(frameset_path, frame_name)
    
    frame = cv2.imread(frame_path, 0)
    
    color_frame = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)
    
    # calculate optical flow
    p1, st, err = cv2.calcOpticalFlowPyrLK(ref_frame, frame, p0, None, **lk_params)
    
    # Select good points
    good_new = p1[st==1]
    good_old = p0[st==1]
    
    # draw the tracks
    for i,(new,old) in enumerate(zip(good_new,good_old)):
        
        a,b = new.ravel()
        c,d = old.ravel()
        mask = cv2.line(mask, (a,b),(c,d), (0,255,0), 2)
        color_frame = cv2.circle(color_frame,(a,b),3,color[i].tolist(),-1)
    
    img = cv2.add(color_frame,mask)
    print("points: ",p1)
    print('------------------------')
    cv2.imshow('frame',color_frame)
    cv2.imshow('mask',img)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
    # Now update the previous frame and previous points
    ref_frame = frame.copy()
    p0 = good_new.reshape(-1,1,2)
cv2.destroyAllWindows()

    



points:  [[[  68.00047302   62.98258209]]

 [[  95.00287628   63.9955101 ]]

 [[ 131.61038208   77.41995239]]

 [[ 189.32078552   71.88136292]]

 [[ 155.54681396   77.88820648]]

 [[ 167.50747681   76.01991272]]

 [[ 167.85749817   82.89792633]]

 [[  49.38916397  153.36050415]]

 [[ 112.64107513   64.09648132]]

 [[ 104.67713165   64.04025269]]

 [[  65.84434509  155.53407288]]

 [[  61.98839188   57.00402069]]

 [[ 216.10122681    9.93055058]]

 [[ 131.99943542   33.01248932]]

 [[ 160.85134888   84.75627136]]

 [[ 117.99996185   35.00762939]]

 [[ 141.99021912   76.92868042]]

 [[  76.01998138   57.99744034]]

 [[  74.77281189  114.49575806]]]
------------------------
points:  [[[  67.99960327   62.98740387]]

 [[  95.01111603   63.99161911]]

 [[ 131.14065552   77.65958405]]

 [[ 189.54820251   72.0719986 ]]

 [[ 155.20481873   78.32596588]]

 [[ 167.2300415    76.15039825]]

 [[ 167.97451782   82.81520844]]

 [[  49.63562393  153.60934448]]

 [[ 112.22354889   64.20817566]]

 [[ 1

points:  [[[  68.12618256   62.8938179 ]]

 [[  94.31439209   63.95843887]]

 [[ 126.42735291   82.34944153]]

 [[ 194.92433167   67.31312561]]

 [[ 149.0198822    82.90315247]]

 [[ 168.69520569   75.27864075]]

 [[ 173.55366516   79.19869232]]

 [[  51.88523102  159.09646606]]

 [[ 107.37911224   65.1446991 ]]

 [[ 101.11802673   64.61657715]]

 [[  61.98051834   57.02730942]]

 [[ 218.20542908    9.33331013]]

 [[ 131.96981812   33.02014923]]

 [[ 157.95457458   88.09703064]]

 [[ 118.00977325   34.99568939]]

 [[ 139.99151611   80.57926178]]

 [[  76.34568787   57.92782211]]

 [[  85.29840851  105.89009857]]]
------------------------
points:  [[[  68.13433838   62.88584518]]

 [[  94.24747467   63.97312927]]

 [[ 126.35978699   82.91085052]]

 [[ 195.465271     67.33156586]]

 [[ 148.66760254   83.18576813]]

 [[ 168.98164368   74.76590729]]

 [[ 173.73374939   78.79094696]]

 [[  51.72597122  159.11129761]]

 [[ 107.41150665   65.23499298]]

 [[ 101.14720154   64.74963379]]

 [[  

points:  [[[  67.93966675   63.09861755]]

 [[  93.14803314   64.15738678]]

 [[ 120.29420471   87.45534515]]

 [[ 200.5960083    63.15706635]]

 [[ 141.54180908   88.98161316]]

 [[ 171.24897766   70.75705719]]

 [[ 176.50205994   74.5163269 ]]

 [[  52.06295013  159.1456604 ]]

 [[ 105.98222351   65.80841064]]

 [[ 100.12347412   65.68386841]]

 [[  61.95806122   57.08420944]]

 [[ 220.43205261    8.74043274]]

 [[ 131.97485352   33.0517807 ]]

 [[ 155.31147766   94.49372101]]

 [[ 117.99023438   35.0348053 ]]

 [[ 134.19476318   86.70272064]]

 [[  75.94369507   58.104599  ]]

 [[  95.80767059   98.19280243]]]
------------------------
points:  [[[  67.93798828   63.10478592]]

 [[  93.07810974   64.18078613]]

 [[ 119.62800598   88.21392822]]

 [[ 200.71763611   63.01651001]]

 [[ 141.07026672   89.30547333]]

 [[ 171.37886047   70.39420319]]

 [[ 176.76972961   74.36699677]]

 [[  51.88367462  159.15518188]]

 [[ 105.59014893   65.8215332 ]]

 [[  99.83708191   65.67749023]]

 [[  

points:  [[[  67.99641418   63.0640831 ]]

 [[  89.59358215   63.40015793]]

 [[ 127.92964935   85.35079956]]

 [[ 205.63945007   58.6410408 ]]

 [[ 132.03753662   95.84113312]]

 [[ 173.6592865    66.89614868]]

 [[ 180.25437927   70.05548096]]

 [[  52.21817017  159.15312195]]

 [[ 101.01622772   66.25841522]]

 [[  95.4642868    65.65145111]]

 [[  61.97674561   57.08250427]]

 [[ 221.94099426    8.09779644]]

 [[ 131.95765686   33.03034973]]

 [[ 146.45458984  101.6778183 ]]

 [[ 118.01483154   35.02397919]]

 [[ 129.6000061    90.2194519 ]]

 [[  76.06908417   58.0656395 ]]

 [[ 104.42602539   94.23742676]]]
------------------------
points:  [[[  68.02690887   63.04819489]]

 [[  89.4318924    63.36818695]]

 [[ 128.99530029   85.04369354]]

 [[ 205.91149902   58.35068893]]

 [[ 132.01089478   96.37197113]]

 [[ 173.501297     66.86373901]]

 [[ 180.2563324    69.68383789]]

 [[  51.91197968  159.14379883]]

 [[ 100.6098175    66.29082489]]

 [[  95.12666321   65.67089081]]

 [[  

points:  [[[  68.05273438   62.94615936]]

 [[  84.399086     63.22875977]]

 [[ 147.56007385   77.81010437]]

 [[ 210.78330994   56.24018097]]

 [[ 131.10162354  100.76157379]]

 [[ 173.72636414   64.84913635]]

 [[ 184.42372131   66.06700134]]

 [[  51.9810791   159.15037537]]

 [[  96.41676331   66.99276733]]

 [[  90.51049805   66.08755493]]

 [[  61.97296143   57.04186249]]

 [[ 224.41906738    7.38102818]]

 [[ 131.83036804   33.0295372 ]]

 [[ 134.84570312  109.58290863]]

 [[ 117.99493408   35.00632477]]

 [[ 146.1295166    89.28746796]]

 [[  76.18548584   57.98430252]]

 [[ 105.62361908   99.13752747]]]
------------------------
points:  [[[  68.04356384   62.91711044]]

 [[  84.22670746   63.24742889]]

 [[ 148.48249817   77.79405975]]

 [[ 211.2429657    56.22789001]]

 [[ 130.58358765  101.41317749]]

 [[ 174.28001404   64.59122467]]

 [[ 184.76168823   65.86756897]]

 [[  52.02933121  159.16424561]]

 [[  96.35546875   66.97740173]]

 [[  90.42073822   66.10883331]]

 [[  

points:  [[[  67.98932648   63.01552582]]

 [[  81.75733185   63.41504669]]

 [[ 159.12718201   71.44686127]]

 [[ 214.77856445   54.52664566]]

 [[ 122.95115662  109.9533844 ]]

 [[ 168.84210205   66.38537598]]

 [[ 188.9604187    62.04942322]]

 [[  51.56724167  159.10719299]]

 [[  95.90499115   66.99220276]]

 [[  88.65128326   66.38592529]]

 [[  61.94370651   57.02164841]]

 [[ 226.23057556    6.65279007]]

 [[ 131.8052063    33.01743317]]

 [[ 125.01522827  119.59462738]]

 [[ 118.5815506    34.78939056]]

 [[ 159.63568115   84.30263519]]

 [[  76.0319519    58.0368576 ]]

 [[  92.70461273  104.2124939 ]]]
------------------------
points:  [[[  68.0122757    63.01200867]]

 [[  81.69526672   63.42857361]]

 [[ 159.31124878   70.81703186]]

 [[ 214.96237183   54.5483284 ]]

 [[ 122.33418274  110.76274872]]

 [[ 168.45196533   66.24836731]]

 [[ 189.3269043    61.69124985]]

 [[  51.72668457  159.10827637]]

 [[  95.92089081   66.99317932]]

 [[  88.60978699   66.38786316]]

 [[  

points:  [[[  68.08895874   62.93142319]]

 [[  81.59270477   63.40433121]]

 [[ 161.41833496   66.71908569]]

 [[ 215.1036377    54.3250351 ]]

 [[ 113.83292389  117.83080292]]

 [[ 166.63179016   63.37226868]]

 [[ 192.67662048   58.27030182]]

 [[  52.31025314  158.90020752]]

 [[  95.97080231   66.95776367]]

 [[  88.65068817   66.34642029]]

 [[  62.00586319   56.94071579]]

 [[ 226.57299805    6.54897261]]

 [[ 133.88175964   33.04869843]]

 [[ 116.07435608  129.41363525]]

 [[ 119.98270416   34.61932373]]

 [[ 169.95994568   79.94289398]]

 [[  76.14670563   57.94521332]]

 [[  72.2698288   110.54101562]]]
------------------------
points:  [[[  68.06770325   62.93558121]]

 [[  81.58169556   63.41868591]]

 [[ 161.3447876    66.73176575]]

 [[ 215.29377747   54.32795334]]

 [[ 113.2898407   117.95188141]]

 [[ 166.80241394   63.27613831]]

 [[ 192.72558594   58.13483047]]

 [[  52.68579102  158.96131897]]

 [[  95.95902252   66.95695496]]

 [[  88.6386795    66.35415649]]

 [[  

points:  [[[  68.05841064   62.91626358]]

 [[  81.56996155   63.42351151]]

 [[ 157.25621033   71.13798523]]

 [[ 218.39839172   54.58377457]]

 [[  98.0724411   126.56032562]]

 [[ 170.63868713   60.62198257]]

 [[ 195.18417358   54.64089203]]

 [[  38.76964951  163.62271118]]

 [[  95.91828156   66.96614075]]

 [[  88.60289001   66.35691833]]

 [[  61.95566559   56.94107819]]

 [[ 228.18977356    6.45229673]]

 [[ 133.87243652   33.07447815]]

 [[ 102.73600769  140.76171875]]

 [[ 119.94467163   34.67152405]]

 [[ 177.61268616   75.53018188]]

 [[  76.13706207   57.94305801]]

 [[  50.87620544  117.49622345]]]
------------------------
points:  [[[  68.05778503   62.92334366]]

 [[  81.54278564   63.42230225]]

 [[ 157.00646973   71.67809296]]

 [[ 218.49560547   54.59944534]]

 [[  97.05702209  127.14588165]]

 [[ 170.90103149   60.25792313]]

 [[ 195.48548889   54.60522079]]

 [[  38.28092575  166.54370117]]

 [[  95.95017242   66.97812653]]

 [[  88.6124115    66.36382294]]

 [[  

points:  [[[  68.07220459   62.93195343]]

 [[  81.53688049   63.41517258]]

 [[ 149.33508301   77.73982239]]

 [[ 216.73971558   54.2430954 ]]

 [[  64.26419067  135.67098999]]

 [[ 177.53387451   55.86576843]]

 [[ 198.46124268   51.22187424]]

 [[  94.55384827   66.81913757]]

 [[  88.62145233   66.36753845]]

 [[  61.97906494   56.95049667]]

 [[ 229.65763855    5.40240574]]

 [[ 133.86157227   33.05226898]]

 [[  95.94577026  155.5652771 ]]

 [[ 120.0050354    34.65282059]]

 [[ 184.16746521   70.04673767]]

 [[  76.10539246   57.97215652]]

 [[  54.75798416  116.77256775]]]
------------------------
points:  [[[  68.06841278   62.9109726 ]]

 [[  81.50048065   63.40023422]]

 [[ 148.81765747   77.79863739]]

 [[ 216.7517395    54.24185181]]

 [[  61.55332947  136.48739624]]

 [[ 177.46083069   55.47439957]]

 [[ 198.61354065   50.85723114]]

 [[  94.32106781   66.77361298]]

 [[  88.59775543   66.35092163]]

 [[  61.98465729   56.93820953]]

 [[ 229.79098511    5.47452927]]

 [[ 1

points:  [[[  68.12513733   62.88143921]]

 [[  81.55133057   63.38502121]]

 [[ 139.3931427    82.87627411]]

 [[ 219.4744873    54.33177567]]

 [[  22.13836288  146.73635864]]

 [[ 179.87113953   51.24276733]]

 [[ 201.8505249    48.51731491]]

 [[  91.02355194   66.4030838 ]]

 [[  86.65714264   65.8604126 ]]

 [[  61.99958801   56.89406204]]

 [[ 230.72717285    5.37070847]]

 [[ 133.88757324   33.02655029]]

 [[ 120.0286026    34.6142807 ]]

 [[ 185.94799805   65.09555054]]

 [[  76.17218018   57.91505814]]

 [[  64.84832764  112.11486816]]]
------------------------
points:  [[[  68.15480042   62.82806015]]

 [[  81.57058716   63.38328934]]

 [[ 138.57229614   83.39255524]]

 [[ 219.51083374   54.32120895]]

 [[  19.70391464  147.36737061]]

 [[ 180.22962952   51.20569611]]

 [[ 202.04373169   48.31987   ]]

 [[  90.89121246   66.4422226 ]]

 [[  86.46128845   65.84805298]]

 [[  61.99790192   56.87835693]]

 [[ 230.79463196    5.33883476]]

 [[ 133.86669922   33.0197525 ]]

 [[ 1

points:  [[[  68.01316833   62.90015411]]

 [[  80.87854767   63.38045883]]

 [[ 126.72663116   90.06488037]]

 [[ 220.69670105   54.51465607]]

 [[ 184.41946411   48.03415298]]

 [[ 204.55352783   46.62948227]]

 [[  89.7101059    66.83200073]]

 [[  81.88666534   65.39855194]]

 [[  61.91626358   56.99514389]]

 [[ 231.46572876    5.81982994]]

 [[ 133.7850647    33.06555939]]

 [[ 120.01086426   34.62017822]]

 [[ 190.78326416   61.07491684]]

 [[  75.87510681   57.93622589]]

 [[  80.93016815  104.8085556 ]]]
------------------------
points:  [[[  68.02114868   62.91513062]]

 [[  80.891716     63.38943481]]

 [[ 126.06595612   90.38328552]]

 [[ 220.71827698   54.53482056]]

 [[ 184.86302185   47.57214355]]

 [[ 204.75440979   46.61712646]]

 [[  89.70057678   66.82670593]]

 [[  81.8516922    65.40054321]]

 [[  61.92037582   56.99637985]]

 [[ 231.48477173    5.82513809]]

 [[ 133.79225159   33.07098007]]

 [[ 119.98202515   34.62739563]]

 [[ 190.96568298   60.72170639]]

 [[  

points:  [[[  67.93740845   63.01368332]]

 [[  80.70755005   63.37857437]]

 [[ 112.27980042   96.74752045]]

 [[ 222.01005554   54.77111816]]

 [[ 187.61894226   48.63604355]]

 [[ 208.54673767   44.72698975]]

 [[  90.03768921   66.84586334]]

 [[  81.9969101    65.38694763]]

 [[  61.9130249    57.0401535 ]]

 [[ 232.07325745    5.98511648]]

 [[ 133.82409668   33.02713776]]

 [[ 120.02798462   34.60349655]]

 [[ 198.10389709   57.77966309]]

 [[  75.65081024   58.02481842]]

 [[  66.60243225  108.34803009]]]
------------------------
points:  [[[  67.93881989   63.00210571]]

 [[  80.74310303   63.38113403]]

 [[ 111.50090027   97.09465027]]

 [[ 222.04086304   54.74756622]]

 [[ 187.34805298   48.9447937 ]]

 [[ 208.72663879   44.69393158]]

 [[  90.11126709   66.84719086]]

 [[  82.14537048   65.41537476]]

 [[  61.9088974    57.03411484]]

 [[ 232.06155396    5.93835115]]

 [[ 133.82003784   33.04136658]]

 [[ 120.02103424   34.60897064]]

 [[ 198.71325684   57.55515289]]

 [[  

In [6]:
help(cv2.imshow)

Help on built-in function imshow:

imshow(...)
    imshow(winname, mat) -> None
    .   @brief Displays an image in the specified window.
    .   
    .   The function imshow displays an image in the specified window. If the window was created with the
    .   cv::WINDOW_AUTOSIZE flag, the image is shown with its original size, however it is still limited by the screen resolution.
    .   Otherwise, the image is scaled to fit the window. The function may scale the image, depending on its depth:
    .   
    .   -   If the image is 8-bit unsigned, it is displayed as is.
    .   -   If the image is 16-bit unsigned or 32-bit integer, the pixels are divided by 256. That is, the
    .   value range [0,255\*256] is mapped to [0,255].
    .   -   If the image is 32-bit or 64-bit floating-point, the pixel values are multiplied by 255. That is, the
    .   value range [0,1] is mapped to [0,255].
    .   
    .   If window was created with OpenGL support, cv::imshow also support ogl::Buffer , og

In [4]:
import cv2
import numpy as np
im =cv2.imread(r'C:\Users\Legion\Documents\standard_test_images\peppers_color.tif')
print(im.shape)

(512, 512, 3)


In [5]:
color = np.random.randint(0,255,(100,3))
im = cv2.line(im,(0,0),(100,100),color[0].tolist(),2)
cv2.imshow('im',im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
k= np.zeros((im.shape[0],im.shape[1],im.shape[2]))
print(k.shape)


(512, 512, 3)


In [1]:
import cv2
import numpy as np

video_path = r'C:\Users\Legion\Desktop\Internship_IIT\Meet_Crowd.mpg'

cap = cv2.VideoCapture(video_path)

feature_params = dict( maxCorners = 100,
                     qualityLevel = 0.3,
                     minDistance = 7,
                     blockSize = 7)

lk_params = dict( winSize = (15, 15),
                maxLevel = 2,
                criteria = (cv2.TERM_CRITERIA_EPS| cv2.TERM_CRITERIA_COUNT, 10,0.03))


color =np.random.randint(0, 255, (100, 3))

ret, old = cap.read()
old_grey = cv2.cvtColor(old, cv2.COLOR_BGR2GRAY)
p0 = cv2.goodFeaturesToTrack(old_grey, mask = None, **feature_params)

mask = np.zeros_like(old)

while(1):
    
    ret, frame = cap.read()
    
    if ret == False:
        break
    
    frame_grey = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    p1, status, err = cv2.calcOpticalFlowPyrLK(old_grey, frame_grey, p0, None, **lk_params)
    
    good_new = p1[status == 1]
    good_old = p0[status == 1]
    
    for idx,(new,old) in enumerate(zip(good_new, good_old)):
        
        a, b = new.ravel()
        c, d = old.ravel()
        
        
        mask = cv2.line(mask, (a, b), (c, d), color[idx].tolist(), 2)
        frame = cv2.circle(frame, (a, b), 5, color[idx].tolist(), -1)
        
    img =cv2.add(frame, mask)
    cv2.imshow('frame', img)
    k = cv2.waitKey(1) & 0xff
    if k == ord('q'):
        break
        
    old_grey = frame_grey.copy()
    p0 = good_new.reshape(-1,1,2)
    
cv2.destroyAllWindows()
cap.release()
    

In [8]:
color[0].


array([248, 113,  69])

In [13]:
import cv2
import numpy as np

frameset_path = input("Enter the frame directory:")

list_frames_name = os.listdir(frameset_path)

if '._.DS_Store' in list_frames_name:
    list_frames_name.remove('._.DS_Store')
    
if '.DS_Store' in list_frames_name:
    list_frames_name.remove('.DS_Store')
    

    
ref_frame_path = os.path.join(frameset_path,list_frames_name[0])
ref_frame = cv2.imread(ref_frame_path,0)
#ref_frame = cv2.resize(ref_frame,(240,240))

prvs = ref_frame

hsv = np.zeros((ref_frame.shape[0],ref_frame.shape[1],3))
hsv[...,1] = 255

for frame_name in list_frames_name[1:]:
    frame_path = os.path.join(frameset_path,frame_name)
    next_img = cv2.imread(frame_path,0)

    flow = cv2.calcOpticalFlowFarneback(prvs,next_img, None, 0.5, 3, 15, 3, 5, 1.2, 0)
    #print(flow)
    #print()
    
    mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])
    print(ang.shape)
    print(mag.shape)
    hsv[...,0] = ang*360/np.pi
    hsv[...,2] = cv2.normalize(mag,None,0,255,cv2.NORM_MINMAX)
    rgb = cv2.cvtColor(np.uint8(hsv),cv2.COLOR_HSV2BGR)
    
    #cv2.imshow('frame',flow)
    cv2.imshow('frame2',rgb)
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
    elif k == ord('s'):
        cv2.imwrite('opticalfb.png',frame2)
        cv2.imwrite('opticalhsv.png',rgb)
    
    prvs = next_img


cv2.destroyAllWindows()

Enter the frame directory:C:\Users\Legion\Desktop\Internship_IIT\UCSD_Anomaly_Dataset.v1p2\UCSDped2\Test\Test001
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 360)
(240, 3

In [3]:
flow.shape

(288, 384, 2)

In [8]:
import numpy as np
import cv2
#import video

help_message = '''
USAGE: opt_flow.py [<video_source>]
Keys:
 1 - toggle HSV flow visualization
 2 - toggle glitch
'''

def draw_flow(img, flow, step=16):
    h, w = img.shape[:2]
    y, x = np.mgrid[step/2:h:step, step/2:w:step].reshape(2,-1)
    fx, fy = flow[y,x].T
    lines = np.vstack([x, y, x+fx, y+fy]).T.reshape(-1, 2, 2)
    lines = np.int32(lines + 0.5)
    vis = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    cv2.polylines(vis, lines, 0, (0, 255, 0))
    for (x1, y1), (x2, y2) in lines:
        cv2.circle(vis, (x1, y1), 1, (0, 255, 0), -1)
    return vis

def draw_hsv(flow):
    h, w = flow.shape[:2]
    fx, fy = flow[:,:,0], flow[:,:,1]
    ang = np.arctan2(fy, fx) + np.pi
    v = np.sqrt(fx*fx+fy*fy)
    hsv = np.zeros((h, w, 3), np.uint8)
    hsv[...,0] = ang*(180/np.pi/2)
    hsv[...,1] = 255
    hsv[...,2] = np.minimum(v*4, 255)
    bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
    return bgr

def warp_flow(img, flow):
    h, w = flow.shape[:2]
    flow = -flow
    flow[:,:,0] += np.arange(w)
    flow[:,:,1] += np.arange(h)[:,np.newaxis]
    res = cv2.remap(img, flow, None, cv2.INTER_LINEAR)
    return res

if __name__ == '__main__':
    
    cap = cv2.VideoCapture(video_path)
    _,prev = cap.read()
    #ret, prev = cam.read()
    prevgray = cv2.cvtColor(prev, cv2.COLOR_BGR2GRAY)
    show_hsv = False
    show_glitch = False
    cur_glitch = prev.copy()

    while True:
        ret, img = cap.read()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        flow = cv2.calcOpticalFlowFarneback(prevgray, gray,None, 0.5, 3, 15, 3, 5, 1.2, 0)
        #flow = cv2.calcOpticalFlowFarneback(prvs,next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
        prevgray = gray
        
        cv2.imshow('flow', draw_flow(gray, flow))
        if show_hsv:
            cv2.imshow('flow HSV', draw_hsv(flow))
        if show_glitch:
            cur_glitch = warp_flow(cur_glitch, flow)
            cv2.imshow('glitch', cur_glitch)

        ch = 0xFF & cv2.waitKey(5)
        if ch == 27:
            break
        if ch == ord('1'):
            show_hsv = not show_hsv
            print('HSV flow visualization is', ['off', 'on'][show_hsv])
        if ch == ord('2'):
            show_glitch = not show_glitch
            if show_glitch:
                cur_glitch = img.copy()
            print('glitch is', ['off', 'on'][show_glitch])
    cv2.destroyAllWindows() 			


IndexError: arrays used as indices must be of integer (or boolean) type

In [9]:
import cv2
import numpy as np


f = cv2.imread(r'C:\Users\Legion\Documents\standard_test_images\peppers_color.tif')

cv2.imshow('frame', f)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
print(f.shape)

(512, 512, 3)


In [17]:
g= cv2.cvtColor(f,cv2.COLOR_BGR2GRAY)
h=cv2.cvtColor(g,cv2.COLOR_GRAY2BGR)

k=np.zeros_like(h)
print(k.shape)

(512, 512, 3)
