In [1]:
import numpy as np

In [6]:
k = np.array([[[ 32. , 46.]],

 [[ 38. , 34.]],

 [[ 27. , 34.]],

 [[ 22. , 46.]]],dtype = int)

In [8]:
n = np.array([[[ 31.9966259 ,  45.99843597]],

 [[ 37.99458313 , 33.98783493]],

 [[ 27.00013351 , 33.99293518]],

 [[ 21.98985291 , 45.99660492]]])

In [12]:
print(n)
print(k)

[[[ 31.9966259   45.99843597]]

 [[ 37.99458313  33.98783493]]

 [[ 27.00013351  33.99293518]]

 [[ 21.98985291  45.99660492]]]
[[[32 46]]

 [[38 34]]

 [[27 34]]

 [[22 46]]]


In [16]:
#for ele in k:
#    n=np.concatenate(n,n.size,ele)
n = np.concatenate((n,k))
print(n)

[[[ 31.9966259   45.99843597]]

 [[ 37.99458313  33.98783493]]

 [[ 27.00013351  33.99293518]]

 [[ 21.98985291  45.99660492]]

 [[ 32.          46.        ]]

 [[ 38.          34.        ]]

 [[ 27.          34.        ]]

 [[ 22.          46.        ]]]


In [43]:
mat =  np.array([[8,0],[0,6]])
u,v =np.linalg.eig(mat)
print(u)
print(v)

max_arg = np.argmax(u)
print(max_arg)

print(v[max_arg])


[ 8.  6.]
[[ 1.  0.]
 [ 0.  1.]]
0
[ 1.  0.]


In [1]:
import cv2
import numpy as np
import time
import os


In [34]:
#calculating the dense optical flow using farneback algorithm

frameset_path = input("Enter the frame directory:")

list_frames_name = os.listdir(frameset_path)

if '._.DS_Store' in list_frames_name:
    list_frames_name.remove('._.DS_Store')
    
if '.DS_Store' in list_frames_name:
    list_frames_name.remove('.DS_Store')
    
    
ref_frame_path = os.path.join(frameset_path,list_frames_name[0])
ref_frame = cv2.imread(ref_frame_path,0)

hsv = np.zeros((ref_frame.shape[0], ref_frame.shape[1], 3))
hsv[...,1] = 255
print(hsv.shape)

print(len(list_frames_name))

for frame_name in list_frames_name[1:]:
    frame_path = os.path.join(frameset_path, frame_name)
    
    frame = cv2.imread(frame_path, 0)
    #print(frame.shape)
    flow = cv2.calcOpticalFlowFarneback(ref_frame, frame, None, 0.5, 5, 15, 3, 5, 1.1, cv2.OPTFLOW_FARNEBACK_GAUSSIAN)
    
    mag, direction = cv2.cartToPolar(flow[...,0],flow[...,1])
    #print(direction.flatten())
    hsv[..., 0] = direction * 180/np.pi
    hsv[..., 2] = cv2.normalize(mag, None, 0, 255, cv2.NORM_MINMAX)
    hsv = np.uint8(hsv)
    bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
    
    cv2.imshow('mask ', bgr)
    cv2.imshow('frame ', frame)
    
    ref_frame = frame
    
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
        
cv2.destroyAllWindows()
print(mag.shape)

Enter the frame directory:C:\Users\Legion\Desktop\Internship_IIT\UCSD_Anomaly_Dataset.v1p2\UCSDped2\Test\Test001
(240, 360, 3)
180
[ 4.9771018   4.5463748   3.80341554 ...,  4.48253345  4.57645464
  4.67544794]
[ 5.37375832  5.54646111  5.66971064 ...,  0.85003209  0.90585673
  1.0990237 ]
[ 1.81339431  1.37959814  1.25224245 ...,  5.66287422  5.83265066
  5.72672987]
[ 2.5675025   2.41069412  2.26212811 ...,  3.03550339  3.03215361
  3.03168416]
[ 0.67987496  0.77672964  0.90080738 ...,  4.42814875  4.3196702
  4.24855328]
[ 1.93120646  2.09948659  2.0331254  ...,  0.12246127  0.14464737
  0.18828939]
[ 1.15176439  1.19681418  1.14942586 ...,  5.92141294  5.69921303
  5.21157503]
[ 1.35910845  1.41963768  1.46743476 ...,  4.14925337  3.86189437
  3.66477942]
[ 2.15825343  2.02852225  1.9872992  ...,  6.0103035   5.71953249
  4.6452775 ]
[ 0.13624264  0.04960204  5.8998313  ...,  5.81841564  5.73648262
  3.66286445]
[ 1.27009797  1.36359656  1.37288249 ...,  0.06754085  0.0261941
  6.1

In [24]:
k=np.zeros((1,2,3))
print(k,k.shape)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]]] (1, 2, 3)


In [9]:
l= cv2.imread(r'C:\Users\Legion\Documents\standard_test_images\mandril_color.tif',1)
print(l.shape)

(512, 512, 3)


In [47]:
k = v[max_arg]
print(k)
np.arctan(1/0)


[ 1.  0.]


ZeroDivisionError: division by zero

In [52]:
np.arctan(np.tan(0))

0.0

In [14]:
import numpy as np
from numpy.linalg import norm, svd

def inexact_augmented_lagrange_multiplier(X, lmbda=.01, tol=1e-4,
                                          maxiter=100, verbose=True):
    """
    Inexact Augmented Lagrange Multiplier
    """
    Y = X
    norm_two = norm(Y.ravel(), 2)
    norm_inf = norm(Y.ravel(), np.inf) / lmbda
    dual_norm = np.max([norm_two, norm_inf])
    Y = Y / dual_norm
    A = np.zeros(Y.shape)
    E = np.zeros(Y.shape)
    dnorm = norm(X, 'fro')
    mu = 1.25 / norm_two
    rho = 1.5
    sv = 10.
    n = Y.shape[0]
    itr = 0
    while True:
        Eraw = X - A + (1 / mu) * Y
        Eupdate = np.maximum(Eraw - lmbda / mu, 0) + np.minimum(Eraw + lmbda / mu, 0)
        U, S, V = svd(X - Eupdate + (1 / mu) * Y, full_matrices=False)
        svp = (S > 1 / mu).shape[0]
        if svp < sv:
            sv = np.min([svp + 1, n])
        else:
            sv = np.min([svp + round(.05 * n), n])
        Aupdate = np.dot(np.dot(U[:, :svp], np.diag(S[:svp] - 1 / mu)), V[:svp, :])
        A = Aupdate
        E = Eupdate
        Z = X - A - E
        Y = Y + mu * Z
        mu = np.min([mu * rho, mu * 1e7])
        itr += 1
        if ((norm(Z, 'fro') / dnorm) < tol) or (itr >= maxiter):
            break
    if verbose:
        print("Finished at iteration %d" % (itr))  
    return A, E

In [6]:
l = np.array([[1,2,3],[66,88,21],[99,57,39]])

import cv2
image  = cv2.imread(r'C:\Users\Legion\Desktop\Internship_IIT\UCSD_Anomaly_Dataset.v1p2\UCSDped2\Test\Test001\112.tif',0)
A,S = inexact_augmented_lagrange_multiplier(l)

cv2.imshow('A',A)
cv2.imshow('S',S)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(A)
print(S)

Finished at iteration 26
[[ 0.00299179 -0.00036024 -0.00105244]
 [-0.00138035 -0.00158685 -0.00246985]
 [-0.00076284 -0.00240055 -0.00115055]]
[[  1.00636919   1.99781983   2.99730402]
 [ 66.00256475  87.99667444  21.0068771 ]
 [ 99.00057883  57.00797386  38.99535132]]


In [3]:
#GODEC algorithm

import numpy as np
from numpy.linalg import norm
from scipy.linalg import qr

def wthresh(a, thresh):
    #Soft wavelet threshold
    res = np.abs(a) - thresh
    return np.sign(a) * ((res > 0) * res)

#Default threshold of .03 is assumed to be for input in the range 0-1...
#original matlab had 8 out of 255, which is about .03 scaled to 0-1 range
def go_dec(X, thresh=.03, rank=2, power=0, tol=1e-3,
           max_iter=100, random_seed=0, verbose=True):
    m, n = X.shape
    if m < n:
        X = X.T
    m, n = X.shape
    L = X
    S = np.zeros(L.shape)
    itr = 0
    random_state = np.random.RandomState(random_seed)    
    while True:
        Y2 = random_state.randn(n, rank)
        for i in range(power + 1):
            Y1 = np.dot(L, Y2)
            Y2 = np.dot(L.T, Y1);
        Q, R = qr(Y2, mode='economic')
        L_new = np.dot(np.dot(L, Q), Q.T)
        T = L - L_new + S
        L = L_new
        S = wthresh(T, thresh)
        T -= S
        err = norm(T.ravel(), 2)
        if (err < tol) or (itr >= max_iter):
            break 
        L += T
        itr += 1
    #Is this even useful in soft GoDec? May be a display issue...
    G = X - L - S
    if m < n:
        L = L.T
        S = S.T
        G = G.T
    if verbose:
        print("Finished at iteration %d" % (itr))
    return L, S, G

In [47]:
l = np.array([[1,2,3],[66,88,21],[99,57,39]])

import cv2
image  = cv2.imread(r'C:\Users\Legion\Desktop\Internship_IIT\UCSD_Anomaly_Dataset.v1p2\UCSDped2\Test\Test001\112.tif',0)
A,S,G = go_dec(image)

mnop = S
m2 = S
print(np.absolute(m2))
print('a:',A)
print('s:',mnop)
print('--------',mnop[0][0])
print('g:',G)

indices = mnop<0
mnop[indices] = 0
cv2.imshow('A',A)
cv2.imshow('S',mnop.T)
cv2.imshow('G', G)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(mnop)

Finished at iteration 100
[[ 25.64567809  25.64885922  26.0278235  ...,  40.57203365  43.12379339
   43.48600438]
 [ 26.17249152  26.17090144  26.56003239 ...,  41.40828684  43.97175358
   44.33602963]
 [ 26.99766361  27.10669868  27.31611915 ...,  39.03166451  41.40494749
   41.77413992]
 ..., 
 [ 29.3809928   27.5343201   19.94549721 ...,  37.45228847  42.20872145
   45.52213717]
 [ 28.67532384  27.85161181  21.22314611 ...,  38.65725669  40.45656214
   43.77116607]
 [ 28.08194415  28.25489176  21.63373559 ...,  39.01354754  38.80437866
   41.1173561 ]]
a: [[  75.67567809   75.67885922   76.0578235  ...,  116.60203365
   117.15379339  117.51600438]
 [  76.20249152   76.20090144   76.59003239 ...,  117.43828684
   118.00175358  118.36602963]
 [  75.02766361   75.13669868   75.34611915 ...,  115.06166451
   115.43494749  115.80413992]
 ..., 
 [  68.5890072    68.4356799    69.02450279 ...,  106.48228847
   107.23872145  107.55213717]
 [  69.29467616   69.11838819   69.74685389 ...,  10

In [51]:
indices = S<0
S[indices] = 0
print(S.T)
print()
print(mnop[0][0])
cv2.imshow('s' ,np.absolute(s_))
cv2.imshow('S', S.T)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  0.           0.           0.         ...,  29.3809928   28.67532384
   28.08194415]
 [  0.           0.           0.         ...,  27.5343201   27.85161181
   28.25489176]
 [  0.           0.           0.         ...,  19.94549721  21.22314611
   21.63373559]
 ..., 
 [  0.           0.           0.         ...,   0.           0.           0.        ]
 [  0.           0.           0.         ...,   0.           0.           0.        ]
 [  0.           0.           0.         ...,   0.           0.           0.        ]]

0.0


In [24]:
l=np.array([[-1,-22,-45],[2,4,5],[-1299,22,45]])
la = np.absolute(l)
print(l)
print(la)

[[   -1   -22   -45]
 [    2     4     5]
 [-1299    22    45]]
[[   1   22   45]
 [   2    4    5]
 [1299   22   45]]


In [53]:
l= np.array([[1,2,3],[22,45,71],[91,2,3]])
a,s,g = go_dec(l)
print(a)
print(s)

Finished at iteration 100
[[  1.00003283   1.91360005   3.01900508]
 [ 21.99999861  45.00126659  70.99919763]
 [ 90.99999997   2.00003163   2.99997997]]
[[ 0.          0.05639995  0.        ]
 [-0.          0.         -0.        ]
 [-0.          0.         -0.        ]]


In [61]:
 x = np.array([[0,0.2,0.5],[0.05,0.01,0]])
    
ind = np.argwhere(x>0.01)
for i in ind:
    a,b = i
    print(x[a,b])

0.2
0.5
0.05


In [63]:
12%4

0

In [10]:
import numpy as np
k = np.array(([[2,3,4],[8,9,6],[10,88,3]]))
l = np.random.randn(100,100)*100
print(l)
print(k[0:2,0:2])

[[-174.51712391   93.97547818  -97.50100453 ..., -209.57144204
    92.89096447  -78.38601862]
 [ -70.74677896  -78.87206124 -142.07088027 ...,  -11.22983627
   117.04547108  120.60777665]
 [ -78.8079064   114.54743502   79.33839689 ...,   -3.41308031  143.9053749
     6.74537942]
 ..., 
 [  -9.23632501  -23.82495173  109.98854713 ...,   97.02097098
    33.84902512  -34.92292784]
 [ -66.02708926 -154.36752821  -65.50450619 ...,  109.98158796
   129.29339367   56.98854853]
 [  32.21950228  -16.73211041  -16.12064276 ...,   32.69921232
   -58.90704281  -76.59829472]]
[[2 3]
 [8 9]]


In [17]:
a,s= inexact_augmented_lagrange_multiplier(l)
print(np.sum(a))
print(np.sum(s))
print(l)
print(a+s)
print(a)
print(s)

Finished at iteration 31
-0.00876882004025
-9815.54760963
[[-174.51712391   93.97547818  -97.50100453 ..., -209.57144204
    92.89096447  -78.38601862]
 [ -70.74677896  -78.87206124 -142.07088027 ...,  -11.22983627
   117.04547108  120.60777665]
 [ -78.8079064   114.54743502   79.33839689 ...,   -3.41308031  143.9053749
     6.74537942]
 ..., 
 [  -9.23632501  -23.82495173  109.98854713 ...,   97.02097098
    33.84902512  -34.92292784]
 [ -66.02708926 -154.36752821  -65.50450619 ...,  109.98158796
   129.29339367   56.98854853]
 [  32.21950228  -16.73211041  -16.12064276 ...,   32.69921232
   -58.90704281  -76.59829472]]
[[-174.51782984   93.97052687  -97.5077192  ..., -209.58607751
    92.88867675  -78.38758889]
 [ -70.74603212  -78.88353961 -142.07520691 ...,  -11.22455011  117.0516736
   120.60646953]
 [ -78.79909418  114.55566891   79.33612136 ...,   -3.41797421
   143.90098745    6.74731736]
 ..., 
 [  -9.23464159  -23.81867513  109.98881828 ...,   97.03375725   33.8366325
   -34.

In [21]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

data = np.array([[-2,-4,2],[-2,1,2],[4,2,5]])
'''
scaler = StandardScaler()
scaler.fit(data)
data = scaler.transform(data)
print(data)
'''
pca = PCA(svd_solver='auto')
pca.fit(data)
print(pca.components_)
print(pca.transform(data))

[[  7.17137166e-01   5.97614305e-01   3.58568583e-01]
 [ -5.34522484e-01   8.01783726e-01  -2.67261242e-01]
 [  4.47213595e-01   6.31845431e-17  -8.94427191e-01]]
[[ -3.98409536e+00  -1.60356745e+00  -6.66133815e-16]
 [ -9.96023841e-01   2.40535118e+00  -3.33066907e-16]
 [  4.98011921e+00  -8.01783726e-01   1.11022302e-15]]
